#
# Module manifest for module 'PowerVCR'
#
# Generated by: Matthew Kelly (Badgerati)
#
# Generated on: 15/06/2020
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'PowerVCR.psm1'

    # Version number of this module.
    ModuleVersion = '$version$'

    # ID used to uniquely identify this module
    GUID = 'a3c256a3-33dc-43e2-9656-a06bca1e08a8'

    # Author of this module
    Author = 'Matthew Kelly (Badgerati)'

    # Copyright statement for this module
    Copyright = 'Copyright (c) 2020 Matthew Kelly (Badgerati), licensed under the MIT License.'

    # Description of the functionality provided by this module
    Description = 'PowerVCR is a Cross-Platform PowerShell web request recorder and playback module.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '6.0'

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @(
        'System.Web',
        'System.Net.Http'
    )

    # Functions to export from this Module
    FunctionsToExport = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('powershell', 'web', 'rest', 'vcr', 'record', 'playback', 'powershell-core',
                'windows', 'unix', 'linux', 'PSEdition_Core', 'cross-platform', 'caching')

            # A URL to the license for this module.
            LicenseUri = 'https://raw.githubusercontent.com/Badgerati/PowerVCR/master/LICENSE.txt'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Badgerati/PowerVCR'

            # Release notes for this particular version of the module
            ReleaseNotes = 'https://github.com/Badgerati/PowerVCR/releases/tag/v$version$'

        }
    }
}